name: Build and Test

on:
  pull_request:
  push:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        VERSION: "DEVELOP"
      run: make docker-build

    - name: Run the Docker image
      run: make run

    - name: Test endpoint responds
      run: |
        sleep 5;curl --verbose --connect-timeout 5 \
        --max-time 10 \
        --retry 5 \
        --retry-delay 0 \
        --retry-max-time 40 http://localhost:5000/version
