# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    tags:
      - version*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    
    - name: Build Release Image
      env:
        VERSION: ${{steps.tag.outputs.tag}}
      run: make docker-build

    - name: Login to Docker Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Tag and Publish Image
      env:
        VERSION: ${{steps.tag.outputs.tag}}
      run: make publish

