# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    tags:
      - version*


jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    
    - name: echo tag
      run: echo "Building image with version ${{steps.tag.outputs.tag}}"

